import { jsPDF } from 'jspdf';

type ContractData = {
  investorName: string;
  investorEmail?: string | null;
  residenceCountry: string;
  taxCountry: string;
  sourceOfFunds: string;
  objective: string;
  horizon: string;
  lossCapacity: string;
  signature?: string;
};

const NAVY = '#073B9A';
const RED = '#F51B2B';
const INK = '#12284D';
const MUTED = '#60769A';
const PALE = '#EEF4FF';

export function createMartinsInvestContract(data: ContractData) {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const width = 210;
  const height = 297;
  const margin = 18;
  const contentWidth = width - margin * 2;

  const setColor = (hex: string) => pdf.setTextColor(hex);
  const header = (section: string, page: number) => {
    pdf.setFillColor(NAVY); pdf.rect(0, 0, width, 8, 'F');
    pdf.setTextColor('#FFFFFF'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(9); pdf.text("MARTIN'S INVEST", margin, 5.5);
    pdf.setTextColor(NAVY); pdf.setFontSize(8); pdf.text(section.toUpperCase(), margin, 17);
    pdf.setDrawColor('#D8E3F2'); pdf.line(margin, 20, width - margin, 20);
    pdf.setTextColor(MUTED); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8); pdf.text(`Contrat modèle · ${page}/22`, width - margin, 17, { align: 'right' });
  };
  const footer = (page: number) => { pdf.setDrawColor('#D8E3F2'); pdf.line(margin, 280, width - margin, 280); setColor(MUTED); pdf.setFontSize(7); pdf.text('Document adaptable · Validation juridique et réglementaire obligatoire avant collecte.', margin, 286); pdf.text(String(page), width - margin, 286, { align: 'right' }); };
  const title = (text: string, y = 31) => { setColor(INK); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(21); pdf.text(text, margin, y); };
  const subtitle = (text: string, y: number) => { setColor(MUTED); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.text(pdf.splitTextToSize(text, contentWidth), margin, y, { lineHeightFactor: 1.5 }); };
  const card = (x: number, y: number, w: number, h: number, fill = PALE) => { pdf.setFillColor(fill); pdf.setDrawColor('#D8E3F2'); pdf.roundedRect(x, y, w, h, 4, 4, 'FD'); };
  const bulletList = (items: string[], y: number, gap = 9) => { items.forEach((item, index) => { pdf.setFillColor(RED); pdf.circle(margin + 2, y + index * gap - 1.3, 1.2, 'F'); setColor(INK); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.text(pdf.splitTextToSize(item, contentWidth - 9), margin + 7, y + index * gap, { lineHeightFactor: 1.4 }); }); };
  const table = (headers: string[], rows: string[][], y: number, widths?: number[]) => { const cols = widths || headers.map(() => contentWidth / headers.length); let x = margin; pdf.setFillColor(NAVY); pdf.rect(margin, y, contentWidth, 9, 'F'); headers.forEach((head, i) => { setColor('#FFFFFF'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(8); pdf.text(head, x + 3, y + 5.8); x += cols[i]; }); rows.forEach((row, r) => { const rowY = y + 9 + r * 14; pdf.setFillColor(r % 2 ? '#F7FAFE' : '#FFFFFF'); pdf.setDrawColor('#D8E3F2'); pdf.rect(margin, rowY, contentWidth, 14, 'FD'); x = margin; row.forEach((value, i) => { setColor(INK); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(7.5); pdf.text(pdf.splitTextToSize(value, cols[i] - 6), x + 3, rowY + 5, { lineHeightFactor: 1.25 }); x += cols[i]; }); }); };
  const chart = (labels: string[], values: number[], y: number, label: string) => { card(margin, y, contentWidth, 67, '#FFFFFF'); setColor(INK); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(10); pdf.text(label, margin + 7, y + 10); const max = Math.max(...values, 1); const baseY = y + 55; const barW = 22; values.forEach((value, i) => { const h = (value / max) * 33; const x = margin + 13 + i * 31; pdf.setFillColor(i === values.length - 1 ? RED : NAVY); pdf.roundedRect(x, baseY - h, barW, h, 2, 2, 'F'); setColor(MUTED); pdf.setFontSize(7); pdf.text(labels[i], x + barW / 2, baseY + 8, { align: 'center' }); pdf.text(`${value}%`, x + barW / 2, baseY - h - 3, { align: 'center' }); }); };
  const standardPage = (section: string, page: number, heading: string, copy: string, items: string[]) => { if (page > 1) pdf.addPage(); header(section, page); title(heading); subtitle(copy, 43); bulletList(items, 78); footer(page); };

  pdf.setFillColor(NAVY); pdf.rect(0, 0, width, height, 'F'); pdf.setDrawColor('#FFFFFF35'); pdf.setLineWidth(.4); pdf.circle(160, 87, 67); pdf.circle(160, 87, 51); pdf.setFillColor(RED); pdf.circle(160, 35, 4, 'F'); pdf.setTextColor('#FFFFFF'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(30); pdf.text("MARTIN'S", margin, 80); pdf.setFontSize(38); pdf.text('INVEST', margin, 99); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(12); pdf.text('Contrat d’accès, d’information et de suivi', margin, 113); pdf.setFontSize(10); pdf.text('Investissement productif · Diaspora & République démocratique du Congo', margin, 126); pdf.setFillColor('#FFFFFF18'); pdf.roundedRect(margin, 164, contentWidth, 54, 5, 5, 'F'); pdf.setFontSize(9); pdf.text('INVESTISSEUR', margin + 9, 179); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(16); pdf.text(data.investorName || 'Investisseur', margin + 9, 190); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(9); pdf.text(`${data.residenceCountry} · Profil créé le ${new Date().toLocaleDateString('fr-FR')}`, margin + 9, 202); pdf.setTextColor('#BFD5FF'); pdf.setFontSize(8); pdf.text('MODÈLE À ADAPTER ET À FAIRE VALIDER PAR LES PROFESSIONNELS COMPÉTENTS', margin, 268); pdf.text('Page 1/22', width - margin, 286, { align: 'right' });

  standardPage('Objet du contrat', 2, 'Objet et périmètre', "Ce document définit les conditions d’utilisation de l’espace Martin’s Invest pour consulter des émissions, préparer un ordre et suivre les informations réconciliées.", ['Martin’s Invest fournit une interface, un dossier numérique, des preuves et des intégrations.', 'Ce contrat ne constitue pas une offre publique, une recommandation personnalisée ni une promesse de rendement.', 'Chaque émission est soumise à sa propre documentation, sa juridiction et ses validations.']);
  standardPage('Responsabilités', 3, 'Les acteurs de l’écosystème', 'Les responsabilités sont séparées pour protéger les investisseurs et éviter toute confusion sur la conservation des fonds.', ['Martin’s Invest orchestre le parcours numérique et le reporting.', 'L’émetteur publie le prospectus, assume les obligations du titre et communique les informations certifiées.', 'La banque dépositaire reçoit et conserve les fonds selon son mandat.', 'Le teneur de registre inscrit les propriétaires et les mouvements.']);
  standardPage('Éligibilité', 4, 'Conditions d’accès', 'L’accès aux fonctionnalités dépend de l’identité, de la résidence, de la fiscalité et des règles applicables au pays de distribution.', ['L’investisseur doit être majeur et fournir des informations exactes.', 'Un profil peut être limité, suspendu ou soumis à une vérification renforcée.', 'Les produits accessibles peuvent varier selon la résidence et la réglementation.', 'Les tickets individuels sont indicativement compris entre 1 000 et 10 000 USD par émission.']);
  standardPage('Profil', 5, 'Votre profil investisseur', `Profil déclaré : ${data.residenceCountry}, fiscalité ${data.taxCountry}, objectif « ${data.objective} », horizon ${data.horizon} ans.`, ['La source des fonds déclarée doit pouvoir être justifiée par des documents proportionnés au risque.', 'Le questionnaire ne garantit pas l’adéquation d’un produit à votre situation.', 'Toute modification importante du profil peut déclencher une nouvelle revue.', 'Les déclarations PEP, sanctions et bénéficiaire effectif doivent rester exactes.']);
  standardPage('KYC / AML', 6, 'Identité et conformité', 'Les contrôles de connaissance client et de lutte contre le blanchiment protègent l’écosystème et peuvent nécessiter une revue humaine.', ['Pièce d’identité, preuve d’adresse, résidence fiscale et présence réelle peuvent être demandées.', 'La source des fonds, la profession et le bénéficiaire effectif peuvent être vérifiés.', 'Les contrôles sanctions, PEP, fraude et risque pays peuvent restreindre un parcours.', 'Aucune information ne doit révéler une déclaration de soupçon ou une procédure confidentielle.']);
  standardPage('Documents', 7, 'Lire avant de décider', 'Aucun ordre ne doit être préparé sans consultation des documents propres à l’émission.', ['Prospectus et document d’informations clés.', 'Scénarios défavorable, intermédiaire et hypothèses de risque.', 'Frais, devise, durée, échéancier, garanties et exclusions.', 'Identité du dépositaire, du teneur de registre et des partenaires vérifiés.']);
  standardPage('Risques', 8, 'Aucun investissement sans risque', 'La valeur d’un investissement peut baisser et le capital peut être partiellement ou totalement perdu.', ['Risque de défaut, retard, illiquidité et restructuration.', 'Risque de change entre USD, CDF et la devise de résidence.', 'Risque de marché, politique, opérationnel, juridique et cybernétique.', 'Les performances passées ne préjugent pas des résultats futurs.']);
  chart(['Marché', 'Change', 'Projet', 'Opérationnel', 'Global'], [34, 49, 42, 27, 39], 105, 'Illustration indicative des familles de risque'); footer(8);
  standardPage('Garanties', 9, 'Garanties et couvertures', 'Une garantie ou une assurance n’existe dans l’interface que si elle est juridiquement active et documentée.', ['Le bénéficiaire, le montant couvert, le rang, les exclusions et l’expiration doivent être identifiables.', 'Un logo public, bancaire ou assurantiel ne constitue pas une garantie.', 'Une réserve peut couvrir une liquidité sans couvrir une perte de capital.', 'Toute couverture réduite ou expirée doit modifier immédiatement l’affichage.']);
  standardPage('Paiement', 10, 'Souscription et conservation des fonds', 'Les paiements sont orientés vers le compte de souscription du dépositaire indiqué par l’émission.', ['Le compte payeur doit correspondre à l’investisseur vérifié.', 'Martin’s Invest ne conserve pas directement les fonds sans agrément correspondant.', 'Un ordre initié ne crée ni titre ni propriété.', 'La confirmation bancaire et l’inscription du teneur de registre sont nécessaires.']);
  table(['Étape', 'Statut', 'Preuve attendue'], [['Ordre', 'Initiée', 'Récapitulatif signé'], ['Paiement', 'Attendu', 'Référence bancaire'], ['Réception', 'Reçu', 'Confirmation dépositaire'], ['Titre', 'Émis', 'Inscription registre']], 108, [38, 38, contentWidth - 76]); footer(10);
  standardPage('Ordres', 11, 'Cycle de vie d’un ordre', 'Chaque étape est horodatée et doit pouvoir être expliquée à l’investisseur.', ['Initiée, signée, paiement attendu, reçu et réconcilié.', 'Un ordre peut être annulé selon les règles de l’émission et le délai de réflexion applicable.', 'Les opérations sensibles sont idempotentes et ne doivent pas être rejouées.', 'Les corrections doivent rester visibles dans l’historique.']);
  standardPage('Portefeuille', 12, 'Portefeuille et propriété', 'Le portefeuille rassemble les positions et les informations réconciliées par le registre, sans remplacer la preuve officielle.', ['Capital investi, valeur déclarée, coupons reçus et intérêts courus.', 'Numéro de titre, dépositaire, teneur de registre et certificat.', 'Allocation par produit, projet, secteur, province et devise.', 'Relevés, échéanciers, audits et documents fiscaux disponibles selon l’émission.']);
  chart(['Produit A', 'Produit B', 'Projet C', 'Réserve'], [35, 25, 28, 12], 105, 'Illustration d’allocation du portefeuille'); footer(12);
  standardPage('Projets', 13, 'Suivi des projets productifs', 'Les projets doivent présenter des données vérifiables sur leur promoteur, leur budget et leurs indicateurs.', ['Promoteur, bénéficiaire effectif, secteur et province.', 'Budget, contrats, permis, fournisseurs et calendrier.', 'Production, ventes, emplois et jalons certifiés.', 'Les pertes, retards et incidents ne doivent pas être masqués.']);
  standardPage('Décaissements', 14, 'Jalons et décaissements', 'Un projet ne reçoit des fonds qu’après contrôles, preuves et approbations séparées.', ['Préparation, apport du promoteur, contrats et premier jalon.', 'Paiement prioritaire aux fournisseurs vérifiés.', 'Blocage automatique en cas d’incident, fraude ou covenant rompu.', 'Aucune personne seule ne peut contrôler la demande, la validation et le paiement.']);
  table(['Jalon', 'Part indicative', 'Contrôle'], [['Préparation', '5 %', 'Permis et sûretés'], ['Apport', '10 %', 'Apport versé'], ['Contrats', '15 %', 'Fournisseurs contrôlés'], ['Exécution', '60 %', 'KPI et réception']], 111, [55, 38, contentWidth - 93]); footer(14);
  standardPage('Change', 15, 'Risque de change', 'Les produits USD restent affichés en USD. Une contre-valeur CDF est indicative et dépend de la source et de l’heure du taux.', ['Le capital contractuel et les coupons ne doivent pas être confondus avec une conversion indicative.', 'Des scénarios de dépréciation CDF de 10 %, 20 %, 30 % et 50 % doivent être présentés.', 'Aucun produit CDF protégé ne doit être affiché sans clause autorisée.', 'Le coût et le risque résiduel de couverture doivent apparaître avant signature.']);
  standardPage('Transparence', 16, 'Reporting et preuves', 'Les informations importantes sont publiées avec leur période, leur source et leur niveau de vérification.', ['Reporting quotidien : souscriptions, rapprochement, liquidité et alertes.', 'Reporting mensuel : collecte, allocation, réserve, exposition et décaissements.', 'Reporting trimestriel : projets, risques, garanties, incidents et KPI.', 'Rapports signés, versionnés et exports tracés.']);
  standardPage('Incidents', 17, 'Incidents et défauts', 'Un incident déclenche une réponse proportionnée, documentée et communiquée selon les obligations applicables.', ['Détection, classification, analyse, confinement et résolution.', 'Gel ciblé des paiements ou décaissements si nécessaire.', 'Conservation des preuves et évaluation de l’impact.', 'Plan correctif, restructuration, recouvrement ou activation d’une couverture si les conditions sont remplies.']);
  standardPage('Données', 18, 'Confidentialité et données personnelles', 'Les données sont traitées pour l’éligibilité, la conformité, la preuve, le suivi et les obligations légales.', ['Minimisation, limitation de finalité et durées de conservation.', 'Chiffrement, contrôle des accès et traçabilité des exports.', 'Droits d’accès et de correction sous réserve des obligations financières et AML.', 'Les données sensibles ne sont pas vendues ni utilisées pour une finalité incompatible.']);
  standardPage('Sécurité', 19, 'Sécurité du compte', 'L’investisseur doit protéger ses moyens d’accès et signaler toute activité inhabituelle.', ['Authentification forte lorsque requise et appareil personnel protégé.', 'Aucun partage de code, mot de passe, signature ou document.', 'Signalement immédiat d’une perte, d’une compromission ou d’une erreur.', 'Les accès privilégiés sont soumis au moindre privilège et à la séparation des rôles.']);
  standardPage('Frais', 20, 'Frais, fiscalité et sorties', 'Les frais propres à une émission doivent être affichés avant toute signature et ne peuvent être remplacés par une estimation opaque.', ['Frais de souscription, tenue, transfert, change, sortie ou administration.', 'Les obligations fiscales dépendent de la résidence et de la nature du produit.', 'Une sortie, un transfert ou un remboursement dépend des règles de l’émission.', 'Les remboursements sont effectués vers un compte vérifié selon la procédure applicable.']);
  standardPage('Utilisation', 21, 'Acceptation et limites', 'En utilisant l’espace Martin’s Invest, l’investisseur confirme avoir compris la nature informative et conditionnelle du service.', ['Les informations saisies sont exactes et peuvent être vérifiées.', 'La lecture du prospectus et des risques reste obligatoire avant tout ordre.', 'Aucune décision ne doit reposer uniquement sur une projection ou une présentation graphique.', 'Les validations réglementaires et contractuelles priment sur toute information d’interface.']);

  pdf.addPage(); header('Signature', 22); title('Signature de l’investisseur'); subtitle('La signature ci-dessous confirme la lecture et l’acceptation du présent modèle. Elle ne vaut pas émission d’un titre ni confirmation de paiement.', 43); card(margin, 72, contentWidth, 44, '#F7FAFE'); setColor(MUTED); pdf.setFontSize(8); pdf.text('INVESTISSEUR', margin + 8, 84); setColor(INK); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(13); pdf.text(data.investorName || 'Investisseur', margin + 8, 94); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8); pdf.text(`${data.investorEmail || 'Email non renseigné'} · ${data.residenceCountry}`, margin + 8, 102); card(margin, 128, contentWidth, 72, '#FFFFFF'); setColor(MUTED); pdf.setFontSize(8); pdf.text('SIGNATURE ÉLECTRONIQUE', margin + 8, 139); pdf.setDrawColor('#9DB9E5'); pdf.line(margin + 8, 184, width - margin - 8, 184); if (data.signature) { try { pdf.addImage(data.signature, 'PNG', margin + 12, 145, 70, 32); } catch { /* Signature image is optional if the browser denies canvas export. */ } } else { setColor('#9AAAC0'); pdf.setFontSize(10); pdf.text('Signature à recueillir dans la plateforme', margin + 8, 164); } setColor(INK); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(9); pdf.text('Version du document', margin, 218); pdf.setFont('helvetica', 'normal'); pdf.text('Martin’s Invest · modèle 1.0 · 17 septembre 2026', margin, 226); pdf.setFont('helvetica', 'bold'); pdf.text('Important', margin, 242); pdf.setFont('helvetica', 'normal'); pdf.text(pdf.splitTextToSize('Ce modèle doit être adapté à chaque émission, à la juridiction concernée et aux contrats effectivement signés avec l’émetteur, le dépositaire et le teneur de registre.', contentWidth), margin, 249, { lineHeightFactor: 1.45 }); footer(22);
  return pdf;
}
