// Centralized Nkampa ecommerce data
export const SELLERS_DATA: Record<string, any> = {
  'seller-1': {
    id: 'seller-1',
    name: 'Kasang Elektronique',
    storeName: 'kasang-elektronique',
    type: 'retailer',
    logo: 'https://picsum.photos/seed/kasang-logo/200/200',
    banner: 'https://picsum.photos/seed/kasang-banner/1200/400',
    location: 'Kinshasa, RDC',
    rating: 4.8,
    reviews: 234,
    verified: true,
    badge: 'Certifié eNKAMBA',
    phone: '+243 XXX XXX XXX',
    email: 'contact@kasang.cd',
    description: 'Kasang Elektronique est le leader en vente d\'électronique en RDC. Nous proposons les meilleurs produits avec garantie et service après-vente.',
    founded: '2015',
    employees: '50+',
    followers: '12.5K',
  },
  'seller-2': {
    id: 'seller-2',
    name: 'Grossiste Goma',
    storeName: 'grossiste-goma',
    type: 'wholesaler',
    logo: 'https://picsum.photos/seed/goma-logo/200/200',
    banner: 'https://picsum.photos/seed/goma-banner/1200/400',
    location: 'Goma, RDC',
    rating: 4.7,
    reviews: 156,
    verified: true,
    badge: 'Certifié eNKAMBA',
    phone: '+243 XXX XXX XXX',
    email: 'contact@goma.cd',
    description: 'Grossiste spécialisé dans la distribution de produits alimentaires et électroniques.',
    founded: '2018',
    employees: '30+',
    followers: '8.2K',
  },
};

export const PRODUCTS_DATA: Record<string, any> = {
  'prod-1': {
    id: 'prod-1',
    sellerId: 'seller-1',
    name: 'iPhone 15 Pro Max',
    price: 1299000,
    originalPrice: 1499000,
    currency: 'CDF',
    rating: 4.8,
    reviews: 234,
    image: 'https://picsum.photos/seed/iphone15/600/600',
    images: [
      'https://picsum.photos/seed/iphone15/600/600',
      'https://picsum.photos/seed/iphone15-2/600/600',
      'https://picsum.photos/seed/iphone15-3/600/600',
      'https://picsum.photos/seed/iphone15-4/600/600',
      'https://picsum.photos/seed/iphone15-5/600/600',
      'https://picsum.photos/seed/iphone15-6/600/600',
    ],
    description: 'Le nouvel iPhone 15 Pro Max avec écran Super Retina XDR, processeur A17 Pro et caméra 48MP.',
    specs: [
      { label: 'Écran', value: '6.7" Super Retina XDR' },
      { label: 'Processeur', value: 'A17 Pro' },
      { label: 'Caméra', value: '48MP + 12MP + 12MP' },
      { label: 'Batterie', value: '4685 mAh' },
      { label: 'Stockage', value: '256GB' },
      { label: 'Couleur', value: 'Titane noir' },
    ],
    stock: 45,
    sold: 120,
    groupBuyPrice: 9000,
    groupBuyMinQty: 3,
    groupBuyCount: 120,
    specialOffer: true,
    offerLabel: 'Offre Spéciale',
    shipping: [
      { name: 'Enkamba Livraison', days: '3-4 jours', icon: '🚚', verified: true },
      { name: 'Diaspora Express', days: '5-7 jours', icon: '✈️', verified: true },
      { name: 'eNKAMBA Logistics', days: '5-7 jours', icon: '🚢', verified: true },
    ],
    paymentMethods: [
      { name: 'eKAMBA Pay', icon: '💳' },
      { name: 'Mobile Money', icon: '📱' },
      { name: 'Carte bancaire', icon: '🏦' },
      { name: 'Paiement à livraison', icon: '💰' },
    ],
  },
  'prod-2': {
    id: 'prod-2',
    sellerId: 'seller-1',
    name: 'Samsung Galaxy S24',
    price: 999000,
    originalPrice: 1199000,
    currency: 'CDF',
    rating: 4.7,
    reviews: 189,
    image: 'https://picsum.photos/seed/samsung-s24/600/600',
    images: [
      'https://picsum.photos/seed/samsung-s24/600/600',
      'https://picsum.photos/seed/samsung-s24-2/600/600',
      'https://picsum.photos/seed/samsung-s24-3/600/600',
    ],
    description: 'Samsung Galaxy S24 avec écran AMOLED 6.1", processeur Snapdragon 8 Gen 3.',
    specs: [
      { label: 'Écran', value: '6.1" AMOLED' },
      { label: 'Processeur', value: 'Snapdragon 8 Gen 3' },
      { label: 'Caméra', value: '50MP + 12MP + 10MP' },
      { label: 'Batterie', value: '4000 mAh' },
      { label: 'Stockage', value: '256GB' },
      { label: 'Couleur', value: 'Noir' },
    ],
    stock: 32,
    sold: 87,
    groupBuyPrice: 8500,
    groupBuyMinQty: 3,
    groupBuyCount: 95,
    specialOffer: false,
    shipping: [
      { name: 'Enkamba Livraison', days: '3-4 jours', icon: '🚚', verified: true },
      { name: 'Diaspora Express', days: '5-7 jours', icon: '✈️', verified: true },
    ],
    paymentMethods: [
      { name: 'eKAMBA Pay', icon: '💳' },
      { name: 'Mobile Money', icon: '📱' },
      { name: 'Carte bancaire', icon: '🏦' },
      { name: 'Paiement à livraison', icon: '💰' },
    ],
  },
  'prod-3': {
    id: 'prod-3',
    sellerId: 'seller-1',
    name: 'MacBook Pro 16"',
    price: 2499000,
    originalPrice: 2799000,
    currency: 'CDF',
    rating: 4.9,
    reviews: 156,
    image: 'https://picsum.photos/seed/macbook/600/600',
    images: [
      'https://picsum.photos/seed/macbook/600/600',
      'https://picsum.photos/seed/macbook-2/600/600',
      'https://picsum.photos/seed/macbook-3/600/600',
    ],
    description: 'MacBook Pro 16" avec processeur M3 Max, 36GB RAM, 512GB SSD.',
    specs: [
      { label: 'Écran', value: '16" Liquid Retina XDR' },
      { label: 'Processeur', value: 'M3 Max' },
      { label: 'RAM', value: '36GB' },
      { label: 'Stockage', value: '512GB SSD' },
      { label: 'Batterie', value: '100Wh' },
      { label: 'Couleur', value: 'Gris sidéral' },
    ],
    stock: 12,
    sold: 45,
    groupBuyPrice: 21000,
    groupBuyMinQty: 2,
    groupBuyCount: 52,
    specialOffer: true,
    offerLabel: 'Stock Limité',
    shipping: [
      { name: 'Enkamba Livraison', days: '3-4 jours', icon: '🚚', verified: true },
      { name: 'Diaspora Express', days: '5-7 jours', icon: '✈️', verified: true },
    ],
    paymentMethods: [
      { name: 'eKAMBA Pay', icon: '💳' },
      { name: 'Carte bancaire', icon: '🏦' },
    ],
  },
  'prod-4': {
    id: 'prod-4',
    sellerId: 'seller-1',
    name: 'iPad Air',
    price: 599000,
    originalPrice: 699000,
    currency: 'CDF',
    rating: 4.6,
    reviews: 98,
    image: 'https://picsum.photos/seed/ipad/600/600',
    images: [
      'https://picsum.photos/seed/ipad/600/600',
      'https://picsum.photos/seed/ipad-2/600/600',
      'https://picsum.photos/seed/ipad-3/600/600',
    ],
    description: 'iPad Air 11" avec processeur M2, écran Liquid Retina.',
    specs: [
      { label: 'Écran', value: '11" Liquid Retina' },
      { label: 'Processeur', value: 'M2' },
      { label: 'RAM', value: '8GB' },
      { label: 'Stockage', value: '256GB' },
      { label: 'Batterie', value: '7606 mAh' },
      { label: 'Couleur', value: 'Bleu ciel' },
    ],
    stock: 28,
    sold: 156,
    groupBuyPrice: 5200,
    groupBuyMinQty: 3,
    groupBuyCount: 189,
    specialOffer: false,
    shipping: [
      { name: 'Enkamba Livraison', days: '3-4 jours', icon: '🚚', verified: true },
      { name: 'Diaspora Express', days: '5-7 jours', icon: '✈️', verified: true },
    ],
    paymentMethods: [
      { name: 'eKAMBA Pay', icon: '💳' },
      { name: 'Mobile Money', icon: '📱' },
      { name: 'Carte bancaire', icon: '🏦' },
      { name: 'Paiement à livraison', icon: '💰' },
    ],
  },
};

export function getProductById(productId: string) {
  return PRODUCTS_DATA[productId];
}

export function getSellerById(sellerId: string) {
  return SELLERS_DATA[sellerId];
}

export function getProductWithSeller(productId: string) {
  const product = getProductById(productId);
  if (!product) return null;
  
  const seller = getSellerById(product.sellerId);
  return {
    ...product,
    seller: {
      id: seller.id,
      name: seller.name,
      storeName: seller.storeName,
      rating: seller.rating,
      reviews: seller.reviews,
      verified: seller.verified,
      location: seller.location,
      badge: seller.badge,
    },
  };
}
