listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
no-multicast-peers
stale-nonce
listening-ip=0.0.0.0
external-ip=${TURN_EXTERNAL_IP}
realm=${TURN_REALM}
server-name=${TURN_DOMAIN}
user=${TURN_USERNAME}:${TURN_PASSWORD}
min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}
no-cli
verbose

# TLS optionnel pour turns:
cert=${TURN_CERT_PATH}
pkey=${TURN_KEY_PATH}

