-- Table de relais des notifications Firebase -> Supabase Realtime
create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  notification_id text not null,
  type text not null,
  title text not null,
  message text not null,
  action_url text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists notification_events_user_id_idx on public.notification_events(user_id);
create index if not exists notification_events_created_at_idx on public.notification_events(created_at desc);

-- Autoriser la lecture côté client anon/auth
alter table public.notification_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'notification_events'
      and policyname = 'read_notification_events'
  ) then
    create policy read_notification_events
    on public.notification_events
    for select
    to anon, authenticated
    using (true);
  end if;
end $$;
